chore: deprecate edx sphinx theme
edx/getsmarter-api-clients pull request #24
Opened 2024-08-02 10:59 UTC by huniafatima-arbi

**Description:**
This PR deprecates `edx-sphinx-theme` and replaces it with `sphinx-book-theme`

**JIRA:** 

**Dependencies:** dependencies on other outstanding PRs, issues, etc. 

**Merge deadline:** List merge deadline (if any)

**Installation instructions:** List any non-trivial installation 
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

2024-08-30 14:54 UTC, iamsobanjaved commented on docs/conf.py
> -# html_theme_options = {}
is this line removal necessary to work, if yes then related comment should also be removed.

2024-08-30 14:54 UTC, iamsobanjaved commented on .github/workflows/ci.yml
> +        toxenv: [quality, docs, 'py39']
We should upgrade the Python version to 3.11 as this is version currently used in most IDAs

2024-08-30 14:54 UTC, iamsobanjaved commented on .github/workflows/ci.yml
> +#      - name: Run Coverage
Was codecov failing here?

2024-08-30 14:54 UTC, iamsobanjaved commented on requirements/doc.txt
> +#    pip-compile --output-file=requirements/doc.txt requirements/doc.in
We should not compile a single file only as it causes inconsistencies in requirements. Instead, we can upgrade a single requirement by temporarily removing the `--upgrade` flag from `pip compile` commands within the make upgrade target.

2024-09-02 13:01 UTC, huniafatima-arbi commented on .github/workflows/ci.yml
> +#      - name: Run Coverage
yes codecov is failing here.

2024-10-30 11:13 UTC, UsamaSadiq requested changes, later dismissed
Can we upgrade it to use `Python 3.12` instead?

2024-11-06 06:27 UTC, iamsobanjaved approved these changes

2024-11-06 14:46 UTC, iloveagent57 approved these changes

2024-11-07 13:56 UTC, merged